---
- name: Install Visual Studio
  hosts: winapps
  # ignore_errors: yes
  become: runas
  tasks:
    - block:
        - name: vs2019 | Check if Visual Studio 2019 Build Tools are installed
          win_stat: path='C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvarsall.bat'
          register: vs2017_installed

        - name: vs2019 | Download the Visual Studio 2019 Build Tools installer
          win_get_url:
             url: 'https://aka.ms/vs/16/release/vs_professional.exe'
             dest: 'C:\Users\Administrator\Downloads\vs_professional.exe'
        - name: 'Check free space in C:'
          win_shell: 'Get-PSDrive C | Select-Object Free | ft -HideTableHeaders'
          register: freespace

        - name: vs2019 | Install Visual Studio 2019 Build Tools
          win_package:
                 path: 'C:\Users\Administrator\Downloads\vs_professional.exe'
                 product_id: Microsoft.VisualStudio.Product.Professional
                 user_name: kalakappavm@myimss.work
                 user_password: Tag31248
                 arguments:
                         --quiet
                         --wait
                         --norestart
                        #- --add Microsoft.VisualStudio.Workload.VCTools ManagedDesktop
                        # - --add Microsoft.VisualStudio.Workload.NetWeb
                        #       - --includeOptional
                        #- --add Microsoft.VisualStudio.Workload.NetCrossPlat
                        #- --add Microsoft.VisualStudio.Workload.NetCoreTools

                      #  when: not vs2017_installed.stat.exists
                      # register: imss
                      #- name: setting up product key
                      #win_shell: |
                      #"vs_setup.exe" --quiet --wait --norestart --lang en-US --productKey BF8Y8-GN2QH-T84XB-QVY3B-RC4DF
          register: imss
      rescue:
         - name: Sending an e-mail using Gmail SMTP servers
           mail:
             host: smtp.gmail.com
             port: 587
             username: imssdevops@gmail.com
             password: xszpyxymsfhgynbp
             to: ajay43mudhol@gmail.com
             subject: Ansible-report
             body: Error while installing MS Visual Studio 2019. "{{ imss.msg }}"
           delegate_to: localhost
           when: imss is failed
